server:
  port: 8081
person:
  last-name: zhangsan
  age: 18
  birth: 2017/11/14
  boss: true
logging.level.com.lbd: debug
#在当前磁盘的根路径下创建spring文件夹和里面的log文件夹，使用spring.log作为默认文件
logging:
  path: /spring/log
  pattern:
    #在控制台输出的日志的格式
    console:
    #指定文件中日志输出的格式
    file:
#不指定路径在当前项目下生成springboot.log日志
#可以指定完整的路径；
#logging:
#  file: d:/springboot.log